services:
  scratch:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ../:/workspaces/scratch:cached
      - pnpm-store:/workspaces/scratch/.pnpm-store
    command: sleep infinity

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    env_file:
      - ./.env
    volumes:
      - postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  postgres-data:
  pnpm-store:
